"""把当前 .env 指向的 MySQL 库导出为可执行的 .sql 文件。

用法（项目根目录）：
  Windows:
    $env:PYTHONPATH="."
    .venv\\Scripts\\python scripts\\export_mysql_sql.py

  Linux:
    export PYTHONPATH=.
    python scripts/export_mysql_sql.py

输出：scripts/out/mysql_edu_crm_agent.sql
"""
from __future__ import annotations

import asyncio
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

from sqlalchemy import text

from config.db_conf import AsyncSessionLocal

OUT = Path(__file__).resolve().parent / "out" / "mysql_edu_crm_agent.sql"

TABLES_IN_ORDER = (
    "student",
    "crm_class",
    "enrollment",
    "work_order",
    "coupon",
    "cash_voucher",
    "refund_order",
    "class_lesson",
    "schedule_change",
    "installment",
    "coupon_refund",
)


def _sql_val(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float, Decimal)):
        return str(v)
    if isinstance(v, datetime):
        return f"'{v.isoformat(sep=' ', timespec='seconds')}'"
    if isinstance(v, date):
        return f"'{v.isoformat()}'"
    s = str(v).replace("\\", "\\\\").replace("'", "''")
    return f"'{s}'"


async def _table_exists(db, name: str) -> bool:
    n = (
        await db.execute(
            text(
                """
                SELECT COUNT(*) FROM information_schema.TABLES
                WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :t
                """
            ),
            {"t": name},
        )
    ).scalar_one()
    return n > 0


async def _show_create(db, name: str) -> str:
    row = (await db.execute(text(f"SHOW CREATE TABLE `{name}`"))).first()
    return row[1] + ";"


async def export() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "-- edu_crm_agent MySQL dump (generated by scripts/export_mysql_sql.py)",
        "SET NAMES utf8mb4;",
        "SET FOREIGN_KEY_CHECKS = 0;",
        "CREATE DATABASE IF NOT EXISTS edu_crm_agent "
        "DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
        "USE edu_crm_agent;",
        "",
    ]

    async with AsyncSessionLocal() as db:
        for table in TABLES_IN_ORDER:
            if not await _table_exists(db, table):
                lines.append(f"-- skip missing table: {table}")
                continue
            lines.append(f"DROP TABLE IF EXISTS `{table}`;")
            lines.append(await _show_create(db, table))
            lines.append("")

            cols = [
                r[0]
                for r in (
                    await db.execute(text(f"SHOW COLUMNS FROM `{table}`"))
                ).all()
            ]
            col_list = ", ".join(f"`{c}`" for c in cols)
            rows = (
                await db.execute(text(f"SELECT * FROM `{table}` ORDER BY id"))
            ).mappings().all()
            if not rows:
                lines.append(f"-- {table}: 0 rows")
                lines.append("")
                continue
            for row in rows:
                vals = ", ".join(_sql_val(row[c]) for c in cols)
                lines.append(f"INSERT INTO `{table}` ({col_list}) VALUES ({vals});")
            lines.append(f"-- {table}: {len(rows)} rows")
            lines.append("")

    lines.append("SET FOREIGN_KEY_CHECKS = 1;")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"written: {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    asyncio.run(export())
